### ISSUE TITLE
Allow wildcards in PedanticDependencyScopeEnforcer

### ISSUE THREAD

**Issue by pkwarren** [ferstl/pedantic-pom-enforcers#36]
It would be very convenient to allow standard Maven wildcards in rules like https://github.com/ferstl/pedantic-pom-enforcers/wiki/PedanticDependencyScopeEnforcer. This way, instead of listing out every Junit jupiter dependency individually in `<testDependencies>`, you could do:

`<testDependencies>junit:*,org.junit.jupiter:*</testDependencies>`.

**Comment by ferstl** [comment]
I implemented wildcard support for the PedanticDependencyScopeEnforcer: https://github.com/ferstl/pedantic-pom-enforcers/wiki/PedanticDependencyScopeEnforcer .
A new release (2.1.0) should be available on Maven Central soon.
